# Generated by Django 5.1.3 on 2024-11-29 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='full name')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='phone number')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', max_length=1)),
                ('position', models.CharField(max_length=4, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price per hour')),
                ('electric_charging', models.BooleanField(default=False, verbose_name='electric charging')),
                ('handicapped', models.BooleanField(default=False)),
                ('covered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='easypark.user')),
                ('manager_code', models.CharField(max_length=200, verbose_name='manager code')),
            ],
            bases=('easypark.user',),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=7, verbose_name='licence plate')),
                ('model', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='easypark.user')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(verbose_name='entry time')),
                ('exit_time', models.DateTimeField(verbose_name='exit time')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='total price')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('PIX', 'Pix')], default='CASH', max_length=4)),
                ('finished', models.BooleanField(default=False)),
                ('payment_confirmed', models.BooleanField(default=False, verbose_name='payment confirmed')),
                ('parking_space', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='easypark.parkingspace')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='easypark.vehicle')),
            ],
        ),
    ]
